In [1]:
import pandas as pd
import numpy as np

In [3]:
monte = pd.Series(['Graham Chapman', 'Johm Cleese'])
monte

0    Graham Chapman
1       Johm Cleese
dtype: object

In [5]:
monte.str.lower()

0    graham chapman
1       johm cleese
dtype: object

In [7]:
monte.str.len()

0    14
1    11
dtype: int64

In [9]:
monte.str.split()

0    [Graham, Chapman]
1       [Johm, Cleese]
dtype: object

In [11]:
monte.str.split('a')

0    [Gr, h, m Ch, pm, n]
1           [Johm Cleese]
dtype: object

In [13]:
monte.str.extract('([A-Za-z]+)')

0
0  Graham
1    Johm

In [15]:
monte.str.findall(r'^[^AEIOU].*[^aeiou]$')

0    [Graham Chapman]
1                  []
dtype: object

In [17]:
monte.str.split().str.get(-1)

0    Chapman
1     Cleese
dtype: object

In [19]:
monte.str[0:2]

0    Gr
1    Jo
dtype: object

In [23]:
full_monte = pd.DataFrame({'name': monte,
                            'info': ['B|C|D', 'B|D']})
full_monte
                           

name   info
0  Graham Chapman  B|C|D
1     Johm Cleese    B|D

In [27]:
full_monte['name'].str.get_dummies('|')

Graham Chapman  Johm Cleese
0               1            0
1               0            1

In [29]:
#Choose June 2020 for date

In [31]:
import sklearn

In [33]:
from sklearn.datasets import load_iris

In [37]:
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [41]:
x = iris.data
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names
print("Feature names: ", feature_names)
print("Target names: ", target_names)
print("\nFirst 10 rows of X: \n", x[:10])

Feature names:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names:  ['setosa' 'versicolor' 'virginica']

First 10 rows of X: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size =0.3, random_state=1)

In [45]:
print(X_train.shape)
print(X_test.shape)

(105, 4)
(45, 4)


In [47]:
print(Y_train.shape)
print(Y_test.shape)

(105,)
(45,)


In [51]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [55]:
#build the model object
classifier_knn = KNeighborsClassifier(n_neighbors=3)

In [57]:
#fit the model
classifier_knn.fit(X_train, Y_train)

KNeighborsClassifier(n_neighbors=3)

In [59]:
#predict on testing dataset
y_pred = classifier_knn.predict(X_test)

In [65]:
print("Response Value:", y_pred)

print("Accuracy: ", metrics.accuracy_score(Y_test, y_pred))

Response Value: [0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 1 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0 1 2 2 0 1 2 1]
Accuracy:  0.9777777777777777


In [67]:
sample = [[5,5,3,2],[2,4,3,5]]
preds = classifier_knn.predict(sample)
pred_species = [iris.target_names[p] for p in preds]
print("Predictions: ", pred_species)

Predictions:  ['versicolor', 'virginica']
