<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 7</p>

We will use the titanic dataset from Kaggle (https://www.kaggle.com/). This is a well-known dataset and we will use it for classification- if the passenger survived or passed away.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
training_DF = pd.read_csv('titanic_dataset_GBC.csv')

In [3]:
training_DF['Age'].fillna(training_DF['Age'].mean(), inplace=True)

In [4]:
training_DF.drop('Cabin',axis=1,inplace=True)

In [5]:
training_DF.dropna(inplace=True)

In [6]:
sex = pd.get_dummies(training_DF['Sex'])
embark = pd.get_dummies(training_DF['Embarked'])

In [7]:
training_DF.drop(['Sex','Embarked','Name','Ticket'],axis=1,inplace=True)

In [8]:
training_DF = pd.concat([training_DF,sex,embark],axis=1)

In [9]:
training_DF.drop(['female','C'],axis=1,inplace=True)

In [18]:
print (training_DF)

     PassengerId  Survived  Pclass        Age  SibSp  Parch     Fare   male  \
0              1         0       3  22.000000      1      0   7.2500   True   
1              2         1       1  38.000000      1      0  71.2833  False   
2              3         1       3  26.000000      0      0   7.9250  False   
3              4         1       1  35.000000      1      0  53.1000  False   
4              5         0       3  35.000000      0      0   8.0500   True   
..           ...       ...     ...        ...    ...    ...      ...    ...   
886          887         0       2  27.000000      0      0  13.0000   True   
887          888         1       1  19.000000      0      0  30.0000  False   
888          889         0       3  29.699118      1      2  23.4500  False   
889          890         1       1  26.000000      0      0  30.0000   True   
890          891         0       3  32.000000      0      0   7.7500   True   

         Q      S  
0    False   True  
1    False 

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(training_DF.drop('Survived',axis=1), 
                                                    training_DF['Survived'], test_size=0.30, 
                                                    random_state=101)

In [26]:
print (X_train)

[[0.90674157 1.         0.23632892 ... 0.         0.         1.        ]
 [0.73146067 0.5        0.23632892 ... 0.         0.         1.        ]
 [0.00224719 1.         0.34542479 ... 0.         0.         1.        ]
 ...
 [0.37977528 1.         0.60452748 ... 1.         0.         1.        ]
 [0.58876404 1.         0.3958696  ... 1.         0.         0.        ]
 [0.97191011 0.5        0.56361653 ... 0.         0.         1.        ]]


In [21]:
print (X_test)


     PassengerId  Pclass        Age  SibSp  Parch    Fare   male      Q      S
511          512       3  29.699118      0      0    8.05   True  False   True
613          614       3  29.699118      0      0    7.75   True   True  False
615          616       2  24.000000      1      2   65.00  False  False   True
337          338       1  41.000000      0      0  134.50  False  False  False
718          719       3  29.699118      0      0   15.50   True   True  False
..           ...     ...        ...    ...    ...     ...    ...    ...    ...
792          793       3  29.699118      8      2   69.55  False  False   True
828          829       3  29.699118      0      0    7.75   True   True  False
732          733       2  29.699118      0      0    0.00   True  False   True
669          670       1  29.699118      1      0   52.00  False  False   True
634          635       3   9.000000      3      2   27.90  False  False   True

[267 rows x 9 columns]


In [22]:
print (y_train)


807    0
651    1
2      1
690    1
196    0
      ..
576    1
840    0
338    1
524    0
865    1
Name: Survived, Length: 622, dtype: int64


In [23]:

print (y_test)

511    0
613    0
615    1
337    1
718    0
      ..
792    0
828    1
732    0
669    1
634    0
Name: Survived, Length: 267, dtype: int64


In [12]:
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)

In [57]:
# let's explore SGDClassifier parameters

'''
SGDClassifier(
    loss='hinge',
    penalty='l2',
    alpha=0.0001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=None,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)
'''

# Let's form SGD models with variation in paameters loss and alpha
    # loss: 'hinge', 'log', and 'modified_huber'
    # alpha: 0.0001 and 0.001
    # explain and dicuss your findings

In [16]:
SGDC_classifier= SGDClassifier(
    loss='hinge',
    penalty='l2',
    alpha=0.0001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=None,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)
SGDC_classifier.fit(X_train, y_train)

SGDClassifier()

In [34]:
X_test = scaler.fit_transform(X_test)
y_pred = SGDC_classifier.predict(X_test)
print(y_pred)


[0 0 1 1 0 0 0 0 0 1 1 1 0 1 0 0 1 1 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1
 0 0 0 1 0 0 1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1
 0 1 0 0 0 0 0 0 1 0 0 1 0 1 0 1 1 1 0 0 0 1 1 0 0 1 0 1 0 0 1 0 1 1 0 0 0
 0 1 1 0 1 0 0 1 1 0 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 1 0 1 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 0
 1 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0
 1 1 0 0 0 0 1 1]


In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[145  18]
 [ 34  70]]


0.8052434456928839

In [30]:
SGDC_classifier_2= SGDClassifier(
    loss='log_loss',
    penalty='l2',
    alpha=0.001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=None,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)
SGDC_classifier_2.fit(X_train, y_train)

SGDClassifier(alpha=0.001, loss='log_loss')

In [35]:
X_test = scaler.fit_transform(X_test)
y_pred_2 = SGDC_classifier_2.predict(X_test)
print(y_pred_2)

[0 0 1 1 0 0 0 0 0 1 1 1 0 1 0 0 1 1 1 0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 1
 0 0 0 1 0 0 1 1 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1 0 0 0 0 1 1
 0 1 0 0 0 0 0 1 1 0 0 1 0 1 0 1 1 1 0 0 0 1 1 0 0 1 0 1 0 0 1 0 1 1 0 1 0
 1 1 1 0 1 0 0 1 1 1 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0
 0 1 0 1 1 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 1 1 0 0 1 0
 1 1 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 1 0 0 0 0 0 0
 1 1 0 0 0 0 1 1]


In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_2)
print(cm)
accuracy_score(y_test, y_pred_2)

[[134  29]
 [ 27  77]]


0.7902621722846442

In [43]:
SGDC_classifier_3= SGDClassifier(
    loss='modified_huber',
    penalty='l2',
    alpha=0.001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=None,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)
SGDC_classifier_3.fit(X_train, y_train)

SGDClassifier(alpha=0.001, loss='modified_huber')

In [44]:
X_test = scaler.fit_transform(X_test)
y_pred_3 = SGDC_classifier_3.predict(X_test)
print(y_pred_3)

[0 0 1 1 0 0 0 0 0 1 1 1 0 1 0 0 1 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1
 0 0 0 1 0 0 1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1
 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 1 0 0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0
 0 1 1 0 1 0 0 1 1 0 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0
 0 1 0 1 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 0
 1 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0
 1 1 0 0 0 0 1 1]


In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_3)
print(cm)
accuracy_score(y_test, y_pred_3)

[[148  15]
 [ 34  70]]


0.8164794007490637