<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 3 </p>

In [1]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det



In [9]:
A = np.array([[5,2,3], [6,1,3],[2,4,1]])
print(A)

[[5 2 3]
 [6 1 3]
 [2 4 1]]


In [13]:
B = A[:2,:2]
print(B)

[[5 2]
 [6 1]]


In [21]:
C = A[1:3, 1:3]
print(C)

[[1 3]
 [4 1]]


In [23]:
D = np.array([[4,-7,4],[5,6,-1],[-4,2,5]])
print(D)

[[ 4 -7  4]
 [ 5  6 -1]
 [-4  2  5]]


In [25]:
AD = np.matmul(A,D)
print(AD)

[[ 18 -17  33]
 [ 17 -30  38]
 [ 24  12   9]]


In [35]:
DA = np.matmul(D,A)
print(DA)
print("DA and AD are not equal")

[[-14  17  -5]
 [ 59  12  32]
 [  2  14  -1]]
DA and AD are not equal


In [31]:
det_B = np.linalg.det(B)
print("Determinant of B: ", det_B)

Determinant of B:  -6.999999999999999


In [33]:
inv_B = np.linalg.inv(B)
print("Inverse of B: ", inv_B)

Inverse of B:  [[-0.14285714  0.28571429]
 [ 0.85714286 -0.71428571]]


In [39]:
inv_D = np.linalg.inv(D)
print("Inverse of D: \n", inv_D)

Inverse of D: 
 [[ 0.07785888  0.10462287 -0.04136253]
 [-0.05109489  0.08759124  0.05839416]
 [ 0.08272506  0.0486618   0.14355231]]


In [41]:
pro1 = np.matmul(D,inv_D)
print(pro1)

[[ 1.00000000e+00  1.11022302e-16  0.00000000e+00]
 [ 6.93889390e-17  1.00000000e+00 -5.55111512e-17]
 [-1.38777878e-17 -8.32667268e-17  1.00000000e+00]]


In [43]:
pro2 = np.matmul(inv_D, D)
print(pro2)

[[ 1.00000000e+00  6.93889390e-17  6.93889390e-18]
 [ 2.77555756e-17  1.00000000e+00 -2.08166817e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
