In [3]:
# importing numpy (and matplotlib)
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
array_2D = np.array([[1,2,3,4],[2,4,6,4],[2,5,6,7]])

In [7]:
print(array_2D)

[[1 2 3 4]
 [2 4 6 4]
 [2 5 6 7]]


In [13]:
print("first fow: ", array_2D[0,1:3])
print("last row: ", array_2D[3,:])

first fow:  [2 3]


IndexError: index 3 is out of bounds for axis 0 with size 3